# Generated by Django 4.1.5 on 2023-05-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=220, unique=True)),
                ('address', models.TextField()),
                ('phone', models.IntegerField(unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.position')),
            ],
        ),
    ]
